### ISSUE TITLE
Password of LynneR is wrong

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/MS-500-Microsoft-365-Security#10]
# Module: 06
#### Step: 07

Description of issue
The password of LynneR is 6npPNil@%AQ and **NOT** Pa55w.rd
Hence the attack will fail
Repro steps:

1.
1.
1.

**Comment by velden** [comment]
The same applies to Task 3 step 6 of the same Exercise

**Comment by bneeb** [comment]
LynneR's password is assigned by your lab hosting provider.  That said I can't find any reference in the instructions to using a different password for LynnR in the area of the labs you reference.
