### ISSUE TITLE
LAB_AK_08_Lab1_Ex3_Compliance_ConditionalAccess.md - Still has Module 7 in title

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-500-Microsoft-365-Security#103]
# Module: 08
## Lab/Demo: 01
Exercise 3
#### Step: 00

Description of issue

Title of this still says module 7:

# Module 7 - Lab 1 - Exercise 3 - Creating compliance and conditional access policies 

Should presumably be:

# Module 8 - Lab 1 - Exercise 3 - Creating compliance and conditional access policies

**Comment by hrasheed-msft** [comment]
@TesterTesterson1004 fixed this issue. Thanks.
