### ISSUE TITLE
Module 9 - Lab 9 - Exercise 1 Microsoft has changed the AIP client in these steps

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-500-Microsoft-365-Security#11]
# Module: 09
#### Steps: 02-04

https://raw.githubusercontent.com/MicrosoftLearning/MS-500-Microsoft-365-Security/master/Instructions/Labs/MS500T00/LAB_AK_01_Lab9_Ex1_Implement_AIP.md
Description of issue

Repro steps:

2. In Microsoft Edge, open a new tab and enter the following URL in the address bar: https://aka.ms/aipclient 
3. On the Download Center page, scroll down to the Microsoft Azure Information Protection section and select Download. 
4. In the Choose the download you want window, select AzInfoProtection.exe and then select Next.

**The client is now**: AzInfoProtection_UL.exe which is the Unified Label client which won't display the label that we created in the Azure portal. 

Workaround: 

Use the Security & Compliance Center where the PII label that we created from the Azure portal is migrated and then we just have to publish it. 
If the authors of the content for this lab want to update the instructions - we should just have the students create the PII label in the Security & Compliance Center.

**Comment by hope77777** [comment]
Hi, Any update on this issue? 
Thanks

**Comment by hope77777** [comment]
Hi, Can we get an update on these issues? Thanks very much.

**Comment by hope77777** [comment]
Hi, Still looking for an update. Thanks.

**Comment by hope77777** [comment]
Any update to this?

**Comment by Valtiter** [comment]
I have the same issue, please provide the correct steps.

**Comment by hope77777** [comment]
Hi, Any update to this? Thanks. its been a while

**Comment by bneeb** [comment]
The AIP lab has been retired because AIP is being deprecated in March 2021.
