### ISSUE TITLE
Module 9 - Lab 9 - Exercise 1 - Implement Azure Information Protection typo

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MS-500-Microsoft-365-Security#12]
# Module: 09
#### Step: 02

https://github.com/MicrosoftLearning/MS-500-Microsoft-365-Security/blob/master/Instructions/Labs/MS500T00/LAB_AK_01_Lab9_Ex1_Implement_AIP.md

Description of issue
at the end of this sentence there is an extra character: A after Word.
In the Search box on the taskbar at the bottom of the window, type Word. In the menu that appears, select Word.**A**

**Comment by bneeb** [comment]
This lab was just retired since AIP is being deprecated in March 2021.
