### ISSUE TITLE
Cannot able to create policy

### ISSUE THREAD

**Issue by sasideepika** [MicrosoftLearning/MS-500-Microsoft-365-Security#126]
# Module: 05
#### Step: 00

Description of issue
Cannot able to create policy
Repro steps:
![image](https://user-images.githubusercontent.com/69594878/147046674-58ecac0a-944c-4c38-937f-fa7a874aaf79.png)

1.Getting the above error while creating policy, Can you help this out @hrasheed-msft  @bneeb @renaudwangler 
1.
1.

**Comment by hrasheed-msft** [comment]
@sasideepika This was a known issue with our old tenans, which should have been resolved. Please let us know if you are still encountering this problem.
