### ISSUE TITLE
Module 8: Intune portal moved

### ISSUE THREAD

**Issue by ISNL-PimP** [MicrosoftLearning/MS-500-Microsoft-365-Security#13]
# Module: 08
#### Task: 02

Microsoft Intune has moved to https://endpoint.microsoft.com/. This makes this lab obsolete, as the next steps are not applicable on the new portal.

**Comment by bneeb** [comment]
You are correct.  Task 2 of this lab exercise is no longer applicable.  Almost the entire module 8 lab is being re-written to accommodate for EndPoint Manager.  That updated lab will be released August 28, 2020.

**Comment by bneeb** [comment]
The entire module 8 has been re-written and will be published in a few minutes.
