### ISSUE TITLE
Module 9 Exercise 2: Intune portal moved to Endpoint Manager

### ISSUE THREAD

**Issue by Valtiter** [MicrosoftLearning/MS-500-Microsoft-365-Security#14]
# Module: 9
#### Step: 6

Description of issue

The Intune portal has been moved to https://endpoint.microsoft.com (Endpoint Manager admin center).

Please provide updated steps, because the existing instructions in the Lab are obsolete.

**Comment by bneeb** [comment]
You are correct.  The entire lab for this module is being re-written to accomodate for EndPoint Manager.  The new lab will be released August 28, 2020.
