### ISSUE TITLE
Module 5 Lab 1 Exercise 1 Task 3 Step 8

### ISSUE THREAD

**Issue by FeckeIT** [MicrosoftLearning/MS-500-Microsoft-365-Security#154]
# Module: 05
#### Step: 08

Description of issue
In Step 8, the group AllCompany must be entered under Group and not under User, otherwise the policy will be created incorrectly (without associated rule)

Repro steps:

1.
1.
1.

**Comment by hsrasheed** [comment]
@FeckeIT We weren't able to reproduce this issue in our latest testing. If you are still experiencing this issue, please let us know.

**Comment by hrasheed-msft** [comment]
@FeckeIT We weren't able to reproduce this issue in our latest testing. If you are still experiencing this issue, please let us know.
