### ISSUE TITLE
Module 6 - Lab 1 - Exercise 1

### ISSUE THREAD

**Issue by FeckeIT** [MicrosoftLearning/MS-500-Microsoft-365-Security#155]
# Module: 06
#### Step: 1 - 9

Description of issue

Attack simulation Training

Task 1 is no longer required in the Microsoft 365 Defender portal, the admin only needs to be assigned the "Attack Simulation Training" role for this purpose

Repro steps:

1.
1.
1.

**Comment by hsrasheed** [comment]
@FeckeIT We weren't able to reproduce this issue in our latest testing. If you are still experiencing this issue, please let us know.

**Comment by hsrasheed** [comment]
#please-close

**Comment by hrasheed-msft** [comment]
@FeckeIT We weren't able to reproduce this issue in our latest testing. If you are still experiencing this issue, please let us know.
