### ISSUE TITLE
MS-500 Module 11 Lab 1, Exercise 2  Verifying DLP Rules

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/MS-500-Microsoft-365-Security#169]
# Module: 11
#### Step: 7

Description of issue

The SSN DLP rule does not fire an alert because the SSNs provided in the lab are invalid.  Instead use valid test SSNs. Valid SSNs can be found from this web site:  https://dlptest.com/sample-data/

One of my students told me about this site.  It is very helpful for testing DLP rules.

Examples of valid test SSNs are:  489-36-8350  514-14-8905 690-05-5315
Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #175.

**Comment by hrasheed-msft** [comment]
@LionelShaul thanks for letting us know. Closing the issue as its been resolved in a PR.
