### ISSUE TITLE
Combined security information registration now default in new tenants.

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-500-Microsoft-365-Security#17]
# Module: 01
##### Steps: 03, 04, 05 (at least)

Description of issue
[**Combined security information registration for Azure Active Directory**](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-registration-mfa-sspr-combined)
**NOTE: Starting on August 15th 2020, all new Azure AD tenants will be automatically enabled for combined registration.**

We either need to update for, or disable combined security information registration.

**Comment by bneeb** [comment]
The labs for this course have just been tested and updated for the latest Microsoft 365 tenant.  The steps have been updated in the repo.
