### ISSUE TITLE
Module 6 - Lab 1 - Exercise 1 

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-500-Microsoft-365-Security#170]
# Module: 6
### Task: 1

Task 1 in this lab is useless, Most protection portal Sims are no longer active. Plus the lab has you go to security portal sims then anyway, So task 1 is wasted steps.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by hrasheed-msft** [comment]
Updated the lab and removed task 1.
