### ISSUE TITLE
Lab list-browsing not working

### ISSUE THREAD

**Issue by reczigabor** [MicrosoftLearning/MS-500-Microsoft-365-Security#171]
# Module: 00
#### Step: 00

Description of issue
The published link with usable-view (content view) has an empty titles: https://microsoftlearning.github.io/MS-500-Microsoft-365-Security/
The items are usable with direct link e.g: https://microsoftlearning.github.io/MS-500-Microsoft-365-Security/Instructions/Labs/MS500T00/LAB_AK_01_Lab1_Ex2_Groups.html

Repro steps:

1.
1.
1.

**Comment by hrasheed-msft** [comment]
@reczigabor This issue has been resolved: https://microsoftlearning.github.io/MS-500-Microsoft-365-Security/

**Comment by reczigabor** [comment]
> @reczigabor This issue has been resolved: https://microsoftlearning.github.io/MS-500-Microsoft-365-Security/

Thank you! G
