### ISSUE TITLE
Password change fails for Allan

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-500-Microsoft-365-Security#18]
# Module: 01
##### Step: 16

Description of issue
"Pa55w.rd" is not accepted for a password change (too easily guessed).

Whatever it is changed to ("Pa55w.rd1234"?), all future sign-ins by Allan will need to be updated.

**Comment by wilkinsanchez** [comment]
I can recommend changing the password as you need to something you can remember.

**Comment by bneeb** [comment]
closed
