### ISSUE TITLE
Module 9 - Lab 1 - Exercise 1 and 2 

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-500-Microsoft-365-Security#192]
#### Step: 06
Thia whole procedure is no longer viable. The Archive has been moved From Compliance back to Exchange Admin Portal.

Exercise 2 is Now done in thew Compliance portal not the Exchange Admin Portal in Exchange Legacy Under Data Lifecycle Management

**Comment by hrasheed-msft** [comment]
@MikeVeschi thanks for your feedback. We have updated Lab 9 after validating the scenario. Verification of the remainder of the labs is in progress. Thank you.
