### ISSUE TITLE
Release preference option not available

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/MS-500-Microsoft-365-Security#194]
# Module 1 - Lab 1 - Exercise 1 - Set up your Microsoft 365 tenant:

Description of issue
We could not find an option of “Release Preferences” in M365 Admin Centre under “Org Setting”.  Seems this option is deprecated and needs to be altered or removed now. 
Please update the lab tasks accordingly. 

Repro steps:
![image](https://user-images.githubusercontent.com/52242119/206538291-682d68e9-07fc-42b0-83b7-002a0d20e1d5.png)

**Comment by sarajfMCT** [comment]
It was a temporary glitch and the option is back.  You could include the direct link in the instructions in case it happens again. The direct link: https://admin.microsoft.com/#/homepage/:/Settings/L1/ReleasePreferences

**Comment by sehrish777** [comment]
Yes it works now, Thanks @sarajfMCT
