### ISSUE TITLE
Deleted Labs

### ISSUE THREAD

**Issue by skagyei** [MicrosoftLearning/MS-500-Microsoft-365-Security#20]
# Module: 00
#### Step: 00

Description of issue
I see there are some missing labs such as AIP and the below. Are you going to re-upload these deleted labs?
Lab: Implement Azure Information Protection and Windows Information Protection
Module 11: Cloud Application Security
Module 12: Compliance in Microsoft 365
Repro steps:

1.
1.
1.

**Comment by WigF1** [comment]
Hi, Skagyei.

The course had a major update at the end of August. You might want to download the changelog. The labs you refer to have been removed from the current version of the course.

(Note, the outline on docs.microsoft.com is now incorrect)

**Comment by skagyei** [comment]
Thanks for the update.

What replaces AIP and the other courses that were deleted?

**Comment by bneeb** [comment]
Labs were updated in August and retested and updated again yesterday.
