### ISSUE TITLE
Module 3 - Lab 2 - Excercise 1 New Experience don't match instructions

### ISSUE THREAD

**Issue by rony-vargas** [MicrosoftLearning/MS-500-Microsoft-365-Security#21]
# Module: 03
#### Step: 01 - 07

Description of issue
Steps doesn't match with the current Azure Privilege Identity Management Experience updated on 07/2020

Now the MFA requests come after the user tries to assume the role from the "My Roles" menu

**Comment by itziktdk** [comment]
Still not aligend with the new experience.. M3-LAB2-4

**Comment by bneeb** [comment]
The labs have just been retested against the latest Microsoft 365 tenant.  The steps have been updated in the repo.
