### ISSUE TITLE
Compatibility issues with IE

### ISSUE THREAD

**Issue by DanielMcKinney-LODS** [MicrosoftLearning/MS-500-Microsoft-365-Security#24]
# Module: 01
#### Step: 21

Description of issue:

Using Internet Explorer; From the Microsoft 365 Admin Center, you are unable to add a member to the  "inside sales group".  
(Groups > Active Groups > Inside sales).  

I was able to confirm that this feature does not work using Internet Explorer inside the lab environment, or locally.  
Using Edge (Chromium), however; you are able to add new members without any issue - Which is available in the work around. 

Note: The lab references the use of Internet Explorer specifically.  

Repro steps:
1. Sign in with tenant.
2. Navigate to active groups. 
3. Attempt to add a member to one of the groups. 

![image](https://user-images.githubusercontent.com/62155069/97625110-1763d580-19f6-11eb-9437-e219075e513c.png)
![image](https://user-images.githubusercontent.com/62155069/97625156-26e31e80-19f6-11eb-8688-f58dc98276d1.png)

**Comment by bneeb** [comment]
The lab instructions have been updated to include Edge browser instead.
