### ISSUE TITLE
UI Change Module 1 - Lab 2 - Exercise 1 Task 2 Step 4

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-500-Microsoft-365-Security#25]
# Module: 01
#### Step: 4

Click My Apps Drop Down upper left, Click My Groups, Click Account Drop Down Upper Right, Click Profile

Edit Security Info, Add Method, Add Phone (should be on step 8)
1.
1.
1.

**Comment by bneeb** [comment]
The labs for this course have just been tested and updated for the latest Microsoft 365 tenant.  The steps have been updated in the repo.
