### ISSUE TITLE
Archiving in Exchange

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/MS-500-Microsoft-365-Security#35]
# Module: 09
#### Step: 01

Description of issue
https://protection.office.com doesn't display Archive.
Repro steps:

1. go to https://compliance.microsoft.com
1.Information Governance
1.Archive

**Comment by hrasheed-msft** [comment]
Hello @CallanTurner. Thanks for reaching out! Yes, you are correct. It seems that this functionality has migrated from the Office 365 security and compliance portal to the Microsoft 365 compliance portal. This will be reflected in an upcoming update this week.

**Comment by hrasheed-msft** [comment]
@CallanTurner The lab has been updated. Please contact us in the future with any other issues. Thank you
