### ISSUE TITLE
Archive Feature Moved Mod 9

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/MS-500-Microsoft-365-Security#36]
# Module: 09
#### Step: 01

Description of issue
https://protection.office.com doesn't display Archive.
Repro steps:

1. go to https://compliance.microsoft.com
1.Information Governance
1.Archive

**Comment by bneeb** [comment]
The labs for this course have been retested with the latest tenant and instructions updated in the main source.
