### ISSUE TITLE
Test self-service password reset changed

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-500-Microsoft-365-Security#37]
# Module: 01
#### Step: 04

Description of issue
MyApps is changed so the procedure to test **self-service password** reset should be updated similar to the instructions in the az-030

https://github.com/MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects/blob/9c4b796257c8483f29c1582ad0dbebe8117ab0a1/Instructions/Mini-labs/Module%2004/02-MiniLab_Enable%20Azure%20AD%20Self-Service%20Password%20Reset.md#test-self-service-password-reset

Repro steps:

1.
1.
1.

**Comment by hrasheed-msft** [comment]
@molenaar Thanks for reaching out. You are correct - the process has changed. We have updated the steps based on your recommendations. They will be published (along with some other lab updates) around end of business today PST. Thanks!

**Comment by hrasheed-msft** [comment]
@molenaar The lab has been updated. Please contact us in the future with any other issues. Thank you
