### ISSUE TITLE
Secure Score delay

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/MS-500-Microsoft-365-Security#4]
# Module: mulitples
#### Step: 00

The Secure Score api takes a lot of time to switch to an active and consistent state.
Meanwhile, every lab/demo based on secure score api (including attack simulations) won't work as depicted. The ordre of this lab should be changed or other topics found ;)

Repro steps:
Create an o365 test tenant and go to Secure Score page.
(in the preview display, a message states the secure score needs 2 - 4 days to begin calcultating score.

**Comment by bneeb** [comment]
Sorry for the slow response.  It seems there were some M365 tenants being created very near the time they were purchased.  This was resulting in the "2-4 days" message regarding calculating secure score.  Now the tenants released are being created at least 5 days prior to being issued which would alleviate this message. from appearing in secure score related labs.

**Comment by bneeb** [comment]
This issue closed.  See last comment.
