### ISSUE TITLE
MS500T00 - Module 8 - Lab 8 - Exercise 3 - Obsolete instructions

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-500-Microsoft-365-Security#5]
# Module: 08
## Lab/Demo: 08
Exercise 3
#### Step: 06-14
(specifically - document https://github.com/MicrosoftLearning/MS-500-Microsoft-365-Security/blob/master/Instructions/Labs/MS500T00/LAB_AK_01_Lab8_Ex3_Create_Intune_Policies.md )

Description of issue
InTune creation process in Azure has changed since instructions were written, the steps from 6-14 thus become somewhat confusing.  These steps could do with an update to reflect current creation process in Azure.
 
Repro steps:

1.
1.
1.

**Comment by bneeb** [comment]
This lab has been re-written and published with Endpoint instructions instead.
