### ISSUE TITLE
Module 6 - Attack Simulator has moved to Security Center

### ISSUE THREAD

**Issue by FeckeIT** [MicrosoftLearning/MS-500-Microsoft-365-Security#67]
# Module: 06
#### Step: all

Description of issue
Attack simulator has moved to Microsoft 365 Security Center, the Lab manual must take new

Module 6 Lab 1 Exercise 2 - Conduct password attacks not possible in new Attack simulation training
Repro steps:

1.
1.
1.

**Comment by hrasheed-msft** [comment]
@FeckeIT Thank you for reaching out! You are correct. The attack simulator has moved and the types of simulations has been reduced. I'll be updating the credential harvesting exercise for the new interface and removing the password attack exercise. Expect an update this Friday afternoon. Thanks.

**Comment by hrasheed-msft** [comment]
@FeckeIT The lab has been updated. Please contact us in the future with any other issues. Thank you
