### ISSUE TITLE
No prompt for change password

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/MS-500-Microsoft-365-Security#7]
# Module: 01
#### Step: 01

Description of issue:
No prompt for change password is displayed. 
Probably because in Lab 1, Exercise 1, Task 3, Step 4 the specific checkbox must be UNchecked (note btw the text of that checkbox isn't 100% accurate: "Make this user change their password when they first sign in" vs. "Require...."

Repro steps:

Just follow the labs

**Comment by velden** [comment]
Additionally: manually changing the password to 'Pa55w.rd' is not possible as it will show a message: 'Choose a password that's harder for people to guess.'

**Comment by bneeb** [comment]
None of what you describe matches the lab instructions.  When the Holly Dickson user is created in lab 1 you are instructed and able to set the password to Pa55w.rd.   You are also instructed to not require the password to be changed on first sign-in.  Therefore when you login as Holly the first time you should not be directed to change the password.  See attached Holly Dickson users setup screen as reference.
![HollyDickson_SetupScreen](https://user-images.githubusercontent.com/12865697/90418370-aa89a200-e07a-11ea-9b19-9f9f195bba83.png)

**Comment by velden** [comment]
I'm sorry. Seems I raised the issue based on old(?) lab instructions. 
Apparently our provider is offering (very) outdated labs,

![image](https://user-images.githubusercontent.com/4172150/90420501-556c8100-e0b8-11ea-8e89-e03ef1b52707.png)
