### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by behymerd** [MicrosoftLearning/MS-500-Microsoft-365-Security#73]
# Module: 01
#### Step: 01

Link is broken for the Microsoft Online Services sign-in Assistant for IT Professionals RTW.

Repro steps:

1.
1.
1.

**Comment by hrasheed-msft** [comment]
@behymerd We have removed this link and the related steps from the lab instructions. It appears that this client is no longer necessary to complete subsequent lab steps. Thanks for reaching out.
