### ISSUE TITLE
Results of Attack Simulation not showing any users

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MS-500-Microsoft-365-Security#81]
# Module: 6
#### Step: 2

Description of issue

After carrying out the simulation as directed (PattiF clicked the link (and did the training too)), the Simulation report shows 0 of 0 users compromised. We checked several times during the simulation and after it concluded (minimum 2 days) and PattiF never showed up in any statistic.

Repro steps:

1. Complete the Lab through Task 4 step 2.
2. View the results

![ms-500 module 6 lab 1 ex 1 task 4 step 2](https://user-images.githubusercontent.com/47234227/121601842-7bcb2680-ca14-11eb-918d-040c76cd456b.JPG)

**Comment by FireyJoe** [comment]
I did this in another instance and got the same result of no results. Maybe it is bugging out from too small a sample?

![image](https://user-images.githubusercontent.com/47234227/127399519-22e4f95d-c879-4af7-8003-d24c8f0e177e.png)

**Comment by hrasheed-msft** [comment]
@FireyJoe I just tested and it works for me as well. I'll close this issue for now - please let us know if you encounter this issue in the future.
