### ISSUE TITLE
TLS 1.2 for Azure AD Connect

### ISSUE THREAD

**Issue by WZot** [MicrosoftLearning/MS-500-Microsoft-365-Security#85]
# Module: 2
### Task: Excerise 1 Task 3

TLS 1.2 is now necessary for setup of Azure AD Connect. Error message send you to a KB-article that tells you how fix this, https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-tls-enforcement ,but the configuration for this should be covered by the lab guide. 

Screenshot of error as shown in this article: https://www.azure365pro.com/upgrading-azure-ad-connect-to-latest-version/

Repro steps:

1. Install Azure AD Connect.
2. Start Azure AD Connect configuration.

**Comment by hrasheed-msft** [comment]
@awillslo Could you check and see if you can reproduce this issue?

**Comment by hsrasheed** [comment]
@WZot We weren't able to reproduce this issue in our latest testing. If you are still experiencing this issue, please let us know.

**Comment by hrasheed-msft** [comment]
@WZot We weren't able to reproduce this issue in our latest testing. If you are still experiencing this issue, please let us know.
