### ISSUE TITLE
Module 14  - Lab 2 - Task 1 - Generate User Data request

### ISSUE THREAD

**Issue by rony-vargas** [MicrosoftLearning/MS-500-Microsoft-365-Security#87]
# Module: 14
#### Step: 4

Description of issue
Console is reporting a en error "The requested resource could not be found"
Repro steps:

1. Click on "New Case"

![ksnip_20210913-204323](https://user-images.githubusercontent.com/49657944/133181443-842d3458-2342-4c00-85dc-c8b08da69897.png)

![ksnip_20210913-204325](https://user-images.githubusercontent.com/49657944/133181475-b742c165-37b0-4f5f-a4cc-cd1125f06af0.png)

**Comment by FireyJoe** [comment]
It looks like this moved, as the warning box suggested. 

On protection.office.com, look under eDiscovery->eDiscovery.
![image](https://user-images.githubusercontent.com/47234227/133286189-db71754c-135b-44c9-8e96-dd17a11e4f45.png)

If coming at it from the compliance.microsoft side, look for User data Search under eDiscovery.

![image](https://user-images.githubusercontent.com/47234227/133286267-75234565-daa8-4672-820f-adad8bbb54a4.png)

**Comment by rony-vargas** [comment]
Hi, thanks @FireyJoe thanks for the comments, that change is already noted, in this case that's not the issue.

I am having issues is whit the error shown in the screenshot red box

**Comment by rony-vargas** [comment]
Looks like this was a bad timing coincidence between the change of nodes from one place to another in the UI, now it doesn't appear under eDiscovery Node, but on it's own node. This was fixed after a complete cache clear on the browser, not it works as expected
![image](https://user-images.githubusercontent.com/49657944/133487222-53ea4a6b-1199-4a6e-82cd-ec8a79cd14a6.png)
