### ISSUE TITLE
New Tenants configured w/all Licenses preapplied.  Need to unassign licenses first.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-500-Microsoft-365-Security#88]
# Module: 01
## Lab/Demo: 01
(exercise 1)
#### Step: 06

Description of issue

Last month (and I believe this is common to all ALHs) the Tenants used by default in this course were changed.  W/the old Tenant I believe there were ~5 licenses not assigned at all.  In the new Tenant all licenses are pre-assigned to the users provided in that Tenant - with no extras to spare.   This leads to an issue of 'no licenses to assign' when one gets to this exer/task/step to assign one to the newly-created Holly user.  

I believe this also becomes an issue somewhat later in Mod2/Lab1/Exer1/Task 4 when we need another license to assign to the (previously local AD user) Abbie Parsons after she is imported into O365.

It seems like it might be a good idea to include some form of 'note' w/some additional steps at or before this portion of the lab instructions, describing the process of un-assigning at least 2 licenses from users that are not used in this course, such that there are licenses to spare when they are needed.

I believe  the users highlighted in yellow below (form the current Tenant) are not utilized at all in MS-500, and thus might be good users to use in any such 'unassign licenses' steps:

![image](https://user-images.githubusercontent.com/49700217/135504655-9fcefc72-d51e-4b04-9914-5be60c622fb4.png)

**Comment by hrasheed-msft** [comment]
@awillslo I can confirm encountering the same issue. Could you please add a few initial steps to free up one or two licenses so that the rest of the steps work as intended?

**Comment by awillslo** [comment]
@hrasheed-msft    see my PR for Mod 2

**Comment by sehrish777** [comment]
I was encountering the same issue. I fixed this by licensing at least 2 users at the start of the lab. try this:
License Freeing up for Holly



1. a. In the **Active Users** window, next to **Adele Vance**, click on three-dots **More actions**. This will give you 4 options. 
1. b. Choose **Manage product licenses**. This will bring you to **Licenses and apps** page. Scroll down and uncheck the boxes for **Microsoft 365 E5** and **Enterprise Mobility + Security E5**. 
1. c. Select **Save Changes** and close this small window of **Adele Vance**. 
1. d. Repeat step "a" to "c" for another user **Christie Cline** and proceed next to step 3.

**Comment by hrasheed-msft** [comment]
Resolved in past PR.
