### ISSUE TITLE
Mod 4, 5 and 6 MFA and missing exersice.

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-500-Microsoft-365-Security#89]
Mod 4 has you enable Registration for self service which going into Mod 5 will require the MFA challenge on Holly if not turned off.

In Mod 6 at bottom of Instructions references an Exercise 2 that is non existent.

**Comment by hrasheed-msft** [comment]
@MikeVeschi I fixed the exercise 2 reference.

Does the MFA remaining on break any of the subsequent lab steps?

**Comment by hrasheed-msft** [comment]
@MikeVeschi @molenaar I'm going to close this issue for now. Let me know if you are still encountering this issue.
