### ISSUE TITLE
Spear phishing - insert the phishing link 

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/MS-500-Microsoft-365-Security#9]
# Module: 06
#### Step: 08

Description of issue

"In the Compose email area enter a creative enticing email message intended to lure users and select Next."
For a working attack (and a nice exercise and example) it's important that the phishing url is inserted in the mail body. However this is not mentioned in this text.

Further:
Task 3, step 3: username is wrong: PattF@... should be PattiF@...

Repro steps:

1.
1.
1.

**Comment by bneeb** [comment]
Hi, in lab 7 exercise 1 task 2 step #4 the note explains that you would ordinarily include a URL.  We chose not to take the exercise that far.  Obviously as an instructor you are free to adjust the lab to include a URL.
